# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix
#

# set-option -g prefix C-g
# unbind C-b
# set -g window-title "tmux"

set -g window-status-format " #I #W "

set -g status-style "bg=#7555ff, fg=color0"

# set -g status-style "bg=black, fg=color0"

# set -g window-status-current-style "bg=color3,fg=#ff0000"

# --- Purple status bar ---
set -g window-status-current-format "#[fg=#7555ff,bg=#1d203c,bold] #I #W #[default]"

# --- Green status bar ---
# set -g window-status-current-format "#[fg=color2,bg=color0,bold] #I #W #[default]"

set -g status-right "%d/%m %H%M"

set-option -g monitor-activity off
set-window-option -g window-status-activity-style none

set -g set-titles on
set -g set-titles-string 'tmux'

set -g mouse on
bind-key s choose-session

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Tab last-window

set -g base-index 1

set -g status-keys vi
set -g history-limit 10000

setw -g mode-keys vi
# setw -g mode-mouse on
setw -g monitor-activity on

# Window splits
# bind-key v split-window -h
# bind-key s split-window -v

# Shift arrow to switch windows
# bind -n S-Left  previous-window
# bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Automatic titles
# set-window-option -g automatic-rename on
# set-option -g set-titles on

# Reload tmux config
bind r source-file ~/.tmux.conf

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection

# This was for debugging, can probably be removed 
# unbind -n h
# unbind -n l
# unbind h
# unbind l
bind-key h swap-window -t -1 \; select-window -t -1
bind-key l swap-window -t +1 \; select-window -t +1

set -g status-left-length 30
set -g status-right ''
set -g status-right-length 0

unbind c
bind c command-prompt -p "Window name:" "new-window -n '%%'"

unbind x
bind x kill-pane
