backend = "glx";
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 8;
fading = true;
fade-delta = 4;

# Exclude Polybar from being affected by blur
no-dnd-shadow = true;
no-dock-shadow = true;
no-dock-shadow-exclude = "class_g = 'Polybar'";
blur-background-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'Dunst'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@:c",
    "class_g = 'Firefox' && window_type = 'popup'"
];

inactive-dim-exclude = [
  "class_g = 'Polybar'"
  "class_g = 'Dunst'"
];
